---
- name: Install nginx with configuration
  hosts: localhost
  become: yes # to run commands with sudo  or root elivated access
  vars:
   server_name: "{{ ansible_default_ipv4.address }}"
   document_root: /var/www
   app_root: html_demo_site-main
  
  tasks:
    - name: install nginx 
      apt:
        name: nginx
        state: latest

    - name: Copy website content to the server
      copy:
       src: "{{ app_root }}"
       dest: "{{ document_root }}"
       mode: preserve
    
    - name: Copy template 
      template:
        src: configs/nginx.conf.j2
        dest: "{{ document_root }}"
      notify: Restart Nginx
    
    - name: Enable new site
      file:
        src: /etc/nginx/sites-available/default
        dest: /etc/nginx/sites-enabled/default
        state: link
      notify: Restart Nginx
    
    - name: Allow all connections on tcp port 80
      ufw:
        rule: allow
        port: 80
        proto: tcp

  handlers:
    - name: Restart Nginx
      service:
        name: nginx
        state: restarted