---
- name: Un-Install nginx
  hosts: localhost
  become: true # to run commands with sudo  or root elivated access
  tasks:

   - name: Stop nginx On debian
     service:
      name: nginx
      enabled: no

   - name: Start nginx service
     apt:
      name: nginx
      state: absent
     


